version: '3.8'

services:
  web_challenge:
    build: .
    container_name: five-finger-discount-web
    ports:
      - "8080:8080"
    environment:
      - FLAG=CLA{flag_flag_flag}
    restart: always