version: '3.8'

services:
  leetcode-challenge:
    build: .
    ports:
      - "1337:1337"
    environment:
      # Hier kannst du deine lokale Test-Flagge eintragen
      - FLAG=CLA{flag_flag_flag}
    restart: always