services:
  printer-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    image: ctf-printer-challenge:1.0
    container_name: ctf_office_printer
    ports:
      - "3000:3000"
    environment:
      - FLAG=CLA{flag_flag_flag}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    restart: always