version: '3.8'

services:
  grpc-reflection-challenge:
    build: .
    container_name: grpc-mirror-challenge
    restart: always
    ports:
      - "50051:50051"
    environment:
      - FLAG=CLA{flag_flag_flag}